services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: https://mirrors.nju.edu.cn/pypi/web/simple
    container_name: agentic-rag-app
    working_dir: /workspace
    command: fastapi dev app/main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
      - ${HOME}/.cache/sentence_transformers:/root/.cache/sentence_transformers
    environment:
      APP_NAME: Agentic RAG
      APP_ENV: dev
      DEBUG: "true"
      QDRANT_HOST: qdrant
      QDRANT_PORT: "6333"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_TEMPERATURE: ${OPENAI_TEMPERATURE}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      TAVILY_SEARCH_DEPTH: ${TAVILY_SEARCH_DEPTH}
      TAVILY_MAX_RESULTS: ${TAVILY_MAX_RESULTS}
      HF_ENDPOINT: https://hf-mirror.com
      HF_HUB_DISABLE_XET: "1"
      HF_HOME: /root/.cache/huggingface
      TRANSFORMERS_CACHE: /root/.cache/huggingface/hub
      SENTENCE_TRANSFORMERS_HOME: /root/.cache/sentence_transformers
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    container_name: agentic-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
